### ISSUE TITLE
Issues with popsicle-transport-http 1.1.3 and n8n (since 0.112.0)

### ISSUE THREAD

**Issue by Rugiagialia** [serviejs/popsicle-transport-http#8] opened 2021-04-26 08:33 UTC
I don't know if someone can help, but with the newest version (1.1.3) I've encountered timeouts with OAUTH2 in **n8n** product.
More details are described [here](https://community.n8n.io/t/connection-errors-since-0-112-0/5006) in n8n community forum

**Comment by blakeembrey** [comment] 2021-04-29 02:55
Thanks for the report, taking a look over this tonight. I'm not entirely sure how n8n is reaching a timeout, I'm guessing it's crashing here and that's resulting in the 504? Either way, I think I have enough to go on for now.

**Comment by blakeembrey** [comment] 2021-04-29 03:48
Ok, I looked through the n8n code and the primary issue appears to be async functions being used but the errors aren't handled: https://github.com/n8n-io/n8n/blob/f4916c7efbff6ec4f76fb7cd948e3ad7f13ac821/packages/cli/src/Server.ts#L1410. That results in any requests timing out if something fails. Would recommend you bring this issue up with them while I keep looking into why you have TLS issues every second request on the latest release. I would recommend something like https://github.com/blakeembrey/async-middleware with express until express has native promise support built in.

**Comment by blakeembrey** [comment] 2021-04-29 03:51
Also, do you happen to know which version of node.js you're using? In case I can't resolve it tonight, it would help me debug further.

**Comment by blakeembrey** [comment] 2021-04-29 04:00
I believe I was able to reproduce an issue using:

```js
const { transport } = require("./dist");
const { Request } = require("servie");

const send = transport();

async function test() {
  const res = await send(new Request("https://login.microsoft.com/"));
  console.log(res.status, res.headers);

  const res1 = await send(new Request(res.headers.get("location")));
  console.log(res1.status, res1.headers);

  const res2 = await send(new Request(res1.headers.get("location")));
  console.log(res2.status, res2.headers);
}

test().then(() => test());
```

It was due to faulty ALPN negotiation. It is now fixed in the latest release.

**Comment by Rugiagialia** [comment] 2021-05-02 15:45
Hello,

I can confirm, that the issue is solved. n8n v 0.118.0 uses the newest popsicle-transport-http 1.1.4, and everything works like a charm.

Thank you very much! 💗

**Closed as completed** 2021-05-02 15:45 UTC
